### ISSUE TITLE
Multiple Test Cases Use Inputs from First Case

### ISSUE THREAD

**Issue by EvanGeer** [geberit/Revit.TestRunner#13]
For example, the test below runs three times with the values from the first case, 12, 3 and 15, but does not iterate through the others. 
![image](https://user-images.githubusercontent.com/49009980/140084549-b1f69c2d-975f-4920-99a9-99f2d518a9c8.png)

**Comment by EvanGeer** [comment]
I have a fix coded, and I am happy to push a Pull Request, but looks like I do not have permissions (or something is up on my end).

Basically I am passing the iterator's index for the multi-case tests to the ReflectionRunner and then using that index to get the correct test case params.

![image](https://user-images.githubusercontent.com/49009980/140087286-84acde35-dcaa-49b8-9c6f-5b80e8b10b5a.png)
![image](https://user-images.githubusercontent.com/49009980/140087357-cfa3d74a-2f31-4d19-9936-203bc7d7fe75.png)

**Comment by tobiasfloescher-geberit** [comment]
Hi, yes you are totally right, this doees not work correctly. 
Thank you for the PR. But I have noticed two problems: 
- There is no assert of the ExpectedResult
- If run only one of the Cases, still the first arguments are passed (12, 3 from the example above)

I will take this in the backlog.

In meanwile, I would recomend using different Test methods, which calling an assert method.

``` C#
[Test]
public void SumTest1() => Sum( 12, 3, 15 );

[Test]
public void SumTest1() => Sum( 13, 7, 20 );

[Test]
public void SumTest1() => Sum( 15, 4, 19 );

private void Sum( int n, int d, int expectedResult )
{
     Assert.AreEqual( n + d, expectedResult );
}
```

**Comment by EvanGeer** [comment]
Ah, good call for a workaround. I will likely still implement a fix on our end to address the assert issue. I may also take a stab at the run once issue as well, since at the root, it might be solved by taking a crack at the timing problem. If I get something workable, I will share with you. 

Side note, this is an awesome product, and I am happy to help develop it. Your implementation (leveraging the idling event to call a test runner) is exactly what I had in mind to build for our team, so I am super excited that you have already done so and shared your solution. If you have any ideas in the pipeline for dev work, I am happy to pick some things up and run with them in my spare time.

**Comment by EvanGeer** [comment]
FWIW, this is the test case I was building off of, which is another viable workaround:

```
        [TestCase("99999 123")]
        [TestCase("99999 2")]
        [TestCase("99999 3")]
        public void Cases(string text)
        {
            Assert.That(TaskDialog.Show(text, $"{text}!!!") == TaskDialogResult.Close);
        }

```

**Comment by tobiasfloescher-geberit** [comment]
Ah, I see your case, no ExpectedResult needed ;)
Happy to hear, that you like the product. Feel free to share your solution, thank you.
