### ISSUE TITLE
Assert.Pass() causes tests to faul

### ISSUE THREAD

**Issue by sylvesp** [geberit/Revit.TestRunner#20]
[Test]
        public void ShouldPassSomeTest()
        {
            Assert.Pass("All is OK");
        }

Assert.Pass() - shouldn't cause the test runner to report failed test.

The fix should probably go into 

        TestInstance.ExecuteTestMethod(...)

to account for NUnit.Framework.SuccessException ?

        
        /// <summary>
        /// Executes the test method.
        /// </summary>
        public async Task ExecuteTestMethod( string methodName )
        {
            var method = Type.GetMethod( methodName );

            try {
                await InvokeMethod( Instance, mSetUp, mPossibleParams );
                await InvokeMethod( Instance, method, mPossibleParams );
            }
            catch(NUnit.Framework.SuccessException e) {
                //Ignore 
            }
            finally {
                await InvokeMethod( Instance, mTearDown, mPossibleParams );
            }
        }

**Comment by tobiasfloescher-geberit** [comment]
Done

**Comment by sylvesp** [comment]
Thanx!
