### ISSUE TITLE
Addin not clickable

### ISSUE THREAD

**Issue by tobiasfloescher-geberit** [geberit/Revit.TestRunner#25]
Hi 
I install the add-in and when I start the Revit, the add-in is not clickable.
Please help me to solve this issue.

_Originally posted by @Kumarravi007 in https://github.com/geberit/Revit.TestRunner/issues/18#issuecomment-1091072899_

**Comment by tobiasfloescher-geberit** [comment]
Hi Tobias

Thanks for the quick reply. 

I try it again without any project loaded in Revit version 2022.

Please correct me if I am wrong, if possible please share a small video which would be very helpful.

Image for reference.
![image](https://user-images.githubusercontent.com/63152994/162146624-54055600-b9bd-4da4-8ef2-340824e80602.png)



Hoping to hear from you soon.

Best

_Originally posted by @Kumarravi007 in https://github.com/geberit/Revit.TestRunner/issues/18#issuecomment-1091206464_

**Comment by tobiasfloescher-geberit** [comment]
Hi @Kumarravi007. You cannot start the TestRunner while a project is open in Revit. Close all projects ant the button is enabled.
In the screenshot you posted, a project is open.

Hope this helps.

![grafik](https://user-images.githubusercontent.com/53896370/162149334-849ff831-ae49-4f84-86fd-02d912739d0d.png)

**Comment by Kumarravi007** [comment]
Thanks for the quick response 
Now I am able to click on the add-in button.

**Comment by tobiasfloescher-geberit** [comment]
Great

**Comment by paolorevit** [comment]
Could you please explain why did you disable addin button when project is open?

**Comment by tobiasfloescher-geberit** [comment]
In my opinion, a test must be something stable, meaning the context must be every time the same. If you run a test on different files, different results may happen. So please load your desired file in the test and do some test stuff then.
