### ISSUE TITLE
To run this application, you must install .Net Core

### ISSUE THREAD

**Issue by paolorevit** [geberit/Revit.TestRunner#27]
I've tried to launch TestRunner inside Revit2023 and received such error.
Then I downloaded and installed .Net Core 3.1 and .Net 6.0, restarted my pc but error remained.
Could you help me please solve that issue?
![NetCore](https://user-images.githubusercontent.com/25610618/180608619-6ae61c8e-2c3b-45b6-b927-54fe7f0d8bc5.png)

**Comment by tobiasfloescher-geberit** [comment]
Hi, installing the NET core runtime should fix the problem. maybe i was not properly installed.
https://www.youtube.com/watch?v=BqYnexZwBPU

The app running on x64 only.

**Comment by paolorevit** [comment]
Hello,
I've installed runtimes but the error still exists

**Comment by tobiasfloescher-geberit** [comment]
This is actually a Windows topic. Try to install the .NET Desktop Runtime from [here](https://dotnet.microsoft.com/en-us/download/dotnet/3.1).

**Comment by paolorevit** [comment]
Thanks a lot. It helped
