### ISSUE TITLE
Cannot Add dll to Test 

### ISSUE THREAD

**Issue by chuongmep** [geberit/Revit.TestRunner#4]
Dear geberit, i have some problem with add file path to test, i has try with more time to test but it not working, if you have any idea,  please help me, thanks you .
Fisrt i do work with a file test and path sample : 
![image](https://user-images.githubusercontent.com/31106432/106440067-fd310c00-64aa-11eb-8081-5e9ecfe024c0.png)
Picture when im select directory to test.
![Screenshot_1](https://user-images.githubusercontent.com/31106432/106439262-12596b00-64aa-11eb-83b3-1c738504e810.png)
and next problem :
![image](https://user-images.githubusercontent.com/31106432/106439504-58163380-64aa-11eb-85dd-32f19b48f131.png)

**Comment by tobiasfloescher-geberit** [comment]
Dear chuongmep
Thank you for trying Revit.TestRunner. This exception looks very strange. It seems that you have an illegal character in your path to the dll, but as I have seen in the picture, this is not the case. This exception is thrown deep in the .net framework.
I cannot reproduce it. For now, I have no idea, sorry. Maybe try to move the sample dll to another path, ex. c:\temp.

Witch windows version do you use? Witch language and regional settings?
Best regards, tobias

**Comment by chuongmep** [comment]
Thanks so much because reply, after i try with laptop in my home , in working normal, my company has block windows **powershell**.This has caused this error, I am currently contacting it for assistance.
