### ISSUE TITLE
Console application Run Test on dll File

### ISSUE THREAD

**Issue by ricaun** [geberit/Revit.TestRunner#7]
Hello,

I was trying to execute some tests using the Console Application without having the JSON sample of the dll. 

In this case, I want to test all the methods on the dll. I suppose the only way to generate de JSON is with the Revit open using the Revit.TestRunner Addin.

I was able to mess with the opensource code and open the Revit then generate the JSON with all the Tests and then run the `RunTests`.

I found this approach a little messy, there is an easy way to do that?

Thanks

**Comment by ricaun** [comment]
I'm actually generating the `RunRequest` using the `ExploreFile`.

Gonna create a PR after some tests!

**Comment by tobiasfloescher-geberit** [comment]
Hello ricaun,

Thank you for your message.

You are right, it is far from convenient and there is no easy way now to run all tests in a dll. A workaround would be to have a specified test inside your dll which calls all other tests dynamically. the RunRequest would contains just this single test.

Definitely need to improve this.

Tobias

**Comment by tobiasfloescher-geberit** [comment]
Feature is placed in the backlog. Issue will be closed.

**Comment by tobiasfloescher-geberit** [comment]
Run all tests of an assembly from console runner is now available.
