### ISSUE TITLE
as shown in the image the compiled class for tests not loaded

### ISSUE THREAD

**Issue by mhakim-bim** [geberit/Revit.TestRunner#8]
![image](https://user-images.githubusercontent.com/65457385/111226243-7fa00600-85e9-11eb-97b9-c2eb03fffff7.png)

**Comment by tobiasfloescher-geberit** [comment]
Ok, you got no response from Revit. Revit must run (Revit 2019) during explore and must not be busy. Maybe you see something in the logfile (link in the upper right) of the UI. The request/responses are stored in the work directory (also link in the upper right).

**Comment by tobiasfloescher-geberit** [comment]
Since I got no more feedback, this issue will be closed.
