### ISSUE TITLE
"Open Runner" button greyed out

### ISSUE THREAD

**Issue by SSeelos** [geberit/Revit.TestRunner#9]
Hi,

I followed the README instructions for Getting started:
got the code -> compiled it -> ran the intallAddin .cmd (v2021)

this successfully created the TestRunner.dll and the TestRunner.addin (pointing to the dll)

when running Revit (2021) though the Button is greyed out:
![image](https://user-images.githubusercontent.com/30175883/120324830-57ba6780-c2e7-11eb-961d-586a8536f6a9.png)

here is the log if that helps:
[Test.Runner.log](https://github.com/geberit/Revit.TestRunner/files/6576304/Test.Runner.log)

**Comment by tobiasfloescher-geberit** [comment]
Hi, the button is only enabled when no document is loaded.

**Comment by SSeelos** [comment]
ok, perfect thank you!
